displayName=Map Autotype
author=Bubbasully15
description=Automatically activates World Map search when the map is opened
tags=map,search,keyboard,worldmap
version=
plugins=com.osrsmapautotype.OsrsMapAutotypePlugin
build=standard