displayName=Map Autotype
author=Bubbasully15
description=Automatically activates world map search when the map is opened
tags=map,search,keyboard,worldmap
plugins=com.osrsmapautotype.OsrsMapAutotypePlugin
version=
build=standard